/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE';
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS';

export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';

export const ENTITY_FAILURE = 'ENTITY_FAILURE';
export const ENTITY_CREATE = 'ENTITY_CREATE';
export const ENTITY_UPDATE = 'ENTITY_UPDATE';
export const ENTITY_FETCH = 'ENTITY_FETCH';
export const ENTITY_DELETE = 'ENTITY_DELETE';
export const SELECT_ENTITY_ITEM = 'SELECT_ENTITY_ITEM';
export const CLEAR_ENTITY_LIST = 'CLEAR_ENTITY_LIST';

/* MENU */
export const MENU_SET_CLASSNAMES = 'MENU_SET_CLASSNAMES';
export const MENU_CONTAINER_ADD_CLASSNAME = 'MENU_CONTAINER_ADD_CLASSNAME';
export const MENU_CLICK_MOBILE_MENU = 'MENU_CLICK_MOBILE_MENU';
export const MENU_CHANGE_DEFAULT_CLASSES = 'MENU_CHANGE_DEFAULT_CLASSES';
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS = 'MENU_CHANGE_HAS_SUB_ITEM_STATUS';